log:
  # level: debug | info | warn | error
  level: debug
  # format: logfmt | json
  format: logfmt 
network:
  # XRPL network URL (testnet, mainnet, or local)
  # https://xrpl.org/docs/tutorials/public-servers
  url: "https://s.devnet.rippletest.net:51234"
  # Network timeout in seconds
  timeout: 30
  # System account configuration
  system:
    # System account address
    account: "rspQjo1QqBZsH3Kbr7Z7SbF7QGRAbWsppE"
    # System account secret (will be redacted in logs)
    secret: "ED314A5DDC93264D2CB91E1ED92B69F9AEDB7FA14027649D3F300B462B0355DEDD"
    # System account public key
    public: "EDF8E0C585E753AF306F88718CAD36968498FDC11C3B762FB8ACEAA6B3AEF59ECD"
server:
  listen: ":8099"
features:
  loan: true