log:
  # level: debug | info | warn | error
  level: info
  # format: logfmt | json
  format: logfmt 
network:
  # XRPL network URL (testnet, mainnet, or local)
  url: "https://s.altnet.rippletest.net:51234/"
  # Network timeout in seconds
  timeout: 30
server:
  listen: ":8099"